### ISSUE TITLE
Task: Log Type on Sidebar

### ISSUE THREAD

**Issue by akaduwel1** [cse110-sp21-group18/Bullet-Journal-App#62]
## Functionality:

-   What page(s) does this issue concern? All Pages
-   What does it do? Goes to the most recent type of log.
-   What CSS components does it use? (ex: buttons, datepicker, text label, ..). Log Buttons on the sidebar, most recent button on the homepage loglist.

## Notes (optional):
In storage, there will be an array "mostRecent" which will hold the most recent of each type. mostRecent[0] will be the name of the most recent daily page, mostRecent[1] will be the name of the most recent weekly page, up until mostRecent[3] which will be the name of the most recent future page. When clicking on one of the logs, read which button the user pressed, and change the page to the correct log.

**Comment by Tekunalogy** [comment]
resolved in pull request #99
