### ISSUE TITLE
Task: Combine Key and Bullet Entries

### ISSUE THREAD

**Issue by akaduwel1** [cse110-sp21-group18/Bullet-Journal-App#69]
## Functionality:

-   What page(s) does this issue concern? Log Pages
-   What does it do? When the Key is clicked, it appears in the bullet entry component that is currently selected by the user.
-   What CSS components does it use? (ex: buttons, datepicker, text label, ..) Key, Bullet Entry

**Comment by Tekunalogy** [comment]
hehe, nice
